service: opensea
useDotenv: true
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  memorySize: 128
functions:
  index_serverless:
    handler: index_serverless.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true